name: "Better Tracking Issue"
description: "🏁 A github action for making tracking issue more easy to manage and see"
author: "loxygenK <me@f4n.dev>"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  token:
    description: GitHub token to access issues.
    required: true
  tag:
    description: A string template added to the head of issue's title. The placeholder `<< id >>` will be substituted by the tracking issue IDs.
    required: false
