name: Build and release

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependnecies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Push and release latest
        run: |
          HEAD=$(git rev-parse HEAD)
          DIRNAME=$(mktemp -d)
          mv dist $DIRNAME/dist
          git fetch origin build-results
          git checkout -b build-results origin/build-results || true
          find ./ -mindepth 1 -not -path "./.git*" -delete
          mv $DIRNAME/dist dist
          ls -al
          git checkout $HEAD action.yml LICENSE
          git config user.name ghost
          git config user.email ghost@ghosttown.example.com
          git add -A

          if [[ ! $(git status -s) ]]; then
            echo "✅ There is no changed file."
            exit 0
          fi

          git commit -m "🚀 Deliver built arifacts at $GITHUB_SHA"
          git tag -f latest
          git log --oneline --graph
          git push origin build-results
          git push -f origin latest  # I am serious, this is to *move* the tag
