name: Build and push

on:
  push:
    branches:
      - main

  pull_request: # Todo: Remove

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependnecies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Push and release latest
        run: |
          git fetch origin build-results
          git checkout -b build-results
          find ./ -mindepth 1 -not -path "./.git*" -not -path "./dist*" -delete
          ls -al
          git checkout main action.yml LICENSE
          git config user.name ghost
          git config user.email ghost@ghosttown.example.com
          git add -A
          git commit -m "🚀 Deliver built arifacts at $GITHUB_SHA"
          git push origin build-results
          git tag -d latest || true
          git tag latest
          git log --oneline --graph
          git push origin latest
