name: Testing

env:
  NODE_VERSION: 16

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependnecies
        run: pnpm install --frozen-lockfile

      - name: Run test
        run: pnpm ci:test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
